"""Mock content database — replace youtube_id values with real Shorts IDs."""

from models import ContentItem, Topic

TOPICS: list[Topic] = [
    Topic(id="programming",   name="Programming",   name_ru="Программирование", icon="💻"),
    Topic(id="economics",     name="Economics",     name_ru="Экономика",         icon="📈"),
    Topic(id="investing",     name="Investing",     name_ru="Инвестиции",        icon="💰"),
    Topic(id="psychology",    name="Psychology",    name_ru="Психология",        icon="🧠"),
    Topic(id="productivity",  name="Productivity",  name_ru="Продуктивность",    icon="⚡"),
    Topic(id="science",       name="Science",       name_ru="Наука",             icon="🔬"),
    Topic(id="languages",     name="Languages",     name_ru="Языки",             icon="🌍"),
    Topic(id="fitness",       name="Fitness",       name_ru="Фитнес",            icon="🏋️"),
]

CONTENT: list[ContentItem] = [
    # ── PROGRAMMING ──────────────────────────────────────────────────────────
    ContentItem(id="p1", title="Python в одну строку — лямбды", creator="Fireship",
        topic="programming", tags=["python","lambda","functional","beginner"],
        duration=58, views=1_200_000, likes=89_000,
        thumbnail_url="https://picsum.photos/seed/p1/400/700",
        youtube_id="rfscVS0vtbw"),
    ContentItem(id="p2", title="Что такое Big O за 60 секунд", creator="ByteByByte",
        topic="programming", tags=["algorithms","big-o","cs-basics","beginner"],
        duration=60, views=980_000, likes=72_000,
        thumbnail_url="https://picsum.photos/seed/p2/400/700",
        youtube_id="__vX2sjlpXU"),
    ContentItem(id="p3", title="Git rebase vs merge — разбор", creator="Traversy Media",
        topic="programming", tags=["git","devops","intermediate","tools"],
        duration=55, views=740_000, likes=61_000,
        thumbnail_url="https://picsum.photos/seed/p3/400/700",
        youtube_id="CRlGDDprdOQ"),
    ContentItem(id="p4", title="Docker за 100 секунд", creator="Fireship",
        topic="programming", tags=["docker","devops","containers","intermediate"],
        duration=100, views=2_100_000, likes=178_000,
        thumbnail_url="https://picsum.photos/seed/p4/400/700",
        youtube_id="Gjnup-PuquQ"),
    ContentItem(id="p5", title="Как работает async/await", creator="Web Dev Simplified",
        topic="programming", tags=["javascript","async","intermediate","web"],
        duration=58, views=890_000, likes=67_000,
        thumbnail_url="https://picsum.photos/seed/p5/400/700",
        youtube_id="V_Kr9OSfDeU"),
    ContentItem(id="p6", title="SQL joins за 5 минут", creator="TechWorld with Nana",
        topic="programming", tags=["sql","database","beginner","backend"],
        duration=57, views=640_000, likes=54_000,
        thumbnail_url="https://picsum.photos/seed/p6/400/700",
        youtube_id="9yeOJ0ZMUYw"),
    ContentItem(id="p7", title="10 паттернов проектирования за 60 сек", creator="Fireship",
        topic="programming", tags=["design-patterns","oop","advanced","architecture"],
        duration=60, views=1_500_000, likes=121_000,
        thumbnail_url="https://picsum.photos/seed/p7/400/700",
        youtube_id="BWprw8Nu4n0"),
    ContentItem(id="p8", title="REST vs GraphQL", creator="Traversy Media",
        topic="programming", tags=["api","graphql","rest","intermediate","web"],
        duration=59, views=720_000, likes=58_000,
        thumbnail_url="https://picsum.photos/seed/p8/400/700",
        youtube_id="PTfZcN20fro"),
    ContentItem(id="p9", title="Как работает хеш-таблица", creator="ByteByByte",
        topic="programming", tags=["data-structures","algorithms","cs-basics","intermediate"],
        duration=57, views=830_000, likes=69_000,
        thumbnail_url="https://picsum.photos/seed/p9/400/700",
        youtube_id="KyUTuwz_b7Q"),
    ContentItem(id="p10", title="Kubernetes за 100 секунд", creator="Fireship",
        topic="programming", tags=["kubernetes","devops","containers","advanced"],
        duration=100, views=1_800_000, likes=145_000,
        thumbnail_url="https://picsum.photos/seed/p10/400/700",
        youtube_id="PziYflu8cB8"),

    # ── ECONOMICS ────────────────────────────────────────────────────────────
    ContentItem(id="e1", title="Почему растёт инфляция — за 60 сек", creator="Crash Course",
        topic="economics", tags=["inflation","macro","beginner","money"],
        duration=60, views=870_000, likes=71_000,
        thumbnail_url="https://picsum.photos/seed/e1/400/700",
        youtube_id="GJ8IgP4BCGs"),
    ContentItem(id="e2", title="ВВП простыми словами", creator="Economics Explained",
        topic="economics", tags=["gdp","macro","beginner","basics"],
        duration=58, views=650_000, likes=52_000,
        thumbnail_url="https://picsum.photos/seed/e2/400/700",
        youtube_id="TrqGLRTlPW0"),
    ContentItem(id="e3", title="Что такое рецессия", creator="Crash Course",
        topic="economics", tags=["recession","macro","beginner","crisis"],
        duration=55, views=740_000, likes=61_000,
        thumbnail_url="https://picsum.photos/seed/e3/400/700",
        youtube_id="x7qIgBDmtGg"),
    ContentItem(id="e4", title="Монополия vs конкуренция", creator="CNBC",
        topic="economics", tags=["micro","competition","markets","intermediate"],
        duration=59, views=520_000, likes=43_000,
        thumbnail_url="https://picsum.photos/seed/e4/400/700",
        youtube_id="Ys9pSEUGgLs"),
    ContentItem(id="e5", title="Как ФРС управляет деньгами", creator="Bloomberg Quicktake",
        topic="economics", tags=["fed","monetary-policy","macro","intermediate","money"],
        duration=60, views=980_000, likes=81_000,
        thumbnail_url="https://picsum.photos/seed/e5/400/700",
        youtube_id="7hRB5_KPIZ0"),
    ContentItem(id="e6", title="Теория игр за одну минуту", creator="TED-Ed",
        topic="economics", tags=["game-theory","micro","advanced","math"],
        duration=58, views=1_100_000, likes=92_000,
        thumbnail_url="https://picsum.photos/seed/e6/400/700",
        youtube_id="M3oWYHYoBvk"),
    ContentItem(id="e7", title="Торговые войны — как это работает", creator="Vox",
        topic="economics", tags=["trade","tariffs","macro","geopolitics","intermediate"],
        duration=57, views=630_000, likes=51_000,
        thumbnail_url="https://picsum.photos/seed/e7/400/700",
        youtube_id="B59m2KIJBFE"),
    ContentItem(id="e8", title="Спрос и предложение — базовый закон", creator="Crash Course",
        topic="economics", tags=["micro","supply-demand","beginner","basics"],
        duration=59, views=1_400_000, likes=113_000,
        thumbnail_url="https://picsum.photos/seed/e8/400/700",
        youtube_id="g9aDizJpd_s"),

    # ── INVESTING ─────────────────────────────────────────────────────────────
    ContentItem(id="i1", title="S&P 500 — что это и как инвестировать", creator="Graham Stephan",
        topic="investing", tags=["etf","index-funds","passive","beginner","stocks"],
        duration=59, views=1_300_000, likes=102_000,
        thumbnail_url="https://picsum.photos/seed/i1/400/700",
        youtube_id="gFQNPmLKj1k"),
    ContentItem(id="i2", title="Сложный процент за 60 секунд", creator="Andrei Jikh",
        topic="investing", tags=["compound-interest","long-term","beginner","math"],
        duration=60, views=890_000, likes=74_000,
        thumbnail_url="https://picsum.photos/seed/i2/400/700",
        youtube_id="0g_eRxVLadc"),
    ContentItem(id="i3", title="Диверсификация портфеля", creator="Two Cents",
        topic="investing", tags=["portfolio","diversification","risk","intermediate","stocks"],
        duration=57, views=670_000, likes=56_000,
        thumbnail_url="https://picsum.photos/seed/i3/400/700",
        youtube_id="an9BiiQyMPc"),
    ContentItem(id="i4", title="Что такое P/E ratio", creator="Financial Times",
        topic="investing", tags=["valuation","pe-ratio","fundamental","intermediate","stocks"],
        duration=58, views=540_000, likes=44_000,
        thumbnail_url="https://picsum.photos/seed/i4/400/700",
        youtube_id="5_ij8Ts5d-Q"),
    ContentItem(id="i5", title="Крипта vs акции — где больше риск", creator="Andrei Jikh",
        topic="investing", tags=["crypto","stocks","risk","comparison","intermediate"],
        duration=60, views=1_100_000, likes=89_000,
        thumbnail_url="https://picsum.photos/seed/i5/400/700",
        youtube_id="1tByXhZcmzs"),
    ContentItem(id="i6", title="DCA стратегия — инвестирование по частям", creator="Graham Stephan",
        topic="investing", tags=["dca","strategy","beginner","long-term","passive"],
        duration=59, views=780_000, likes=64_000,
        thumbnail_url="https://picsum.photos/seed/i6/400/700",
        youtube_id="9Yxm2L5LHVY"),
    ContentItem(id="i7", title="REITs — недвижимость без покупки квартиры", creator="Dividend Bull",
        topic="investing", tags=["reits","real-estate","passive","income","intermediate"],
        duration=58, views=490_000, likes=40_000,
        thumbnail_url="https://picsum.photos/seed/i7/400/700",
        youtube_id="yDrQcpWGCgE"),
    ContentItem(id="i8", title="Облигации — зачем они нужны в портфеле", creator="Two Cents",
        topic="investing", tags=["bonds","portfolio","fixed-income","intermediate","risk"],
        duration=57, views=430_000, likes=35_000,
        thumbnail_url="https://picsum.photos/seed/i8/400/700",
        youtube_id="u4SVVXKyvIM"),

    # ── PSYCHOLOGY ────────────────────────────────────────────────────────────
    ContentItem(id="ps1", title="Когнитивные искажения — топ-5", creator="Kurzgesagt",
        topic="psychology", tags=["cognitive-bias","thinking","beginner","mind"],
        duration=60, views=2_100_000, likes=185_000,
        thumbnail_url="https://picsum.photos/seed/ps1/400/700",
        youtube_id="UBVV8pch1dM"),
    ContentItem(id="ps2", title="Почему мы прокрастинируем", creator="TED-Ed",
        topic="psychology", tags=["procrastination","behavior","beginner","motivation"],
        duration=59, views=1_600_000, likes=134_000,
        thumbnail_url="https://picsum.photos/seed/ps2/400/700",
        youtube_id="arj7oStGLkU"),
    ContentItem(id="ps3", title="Эффект Даннинга-Крюгера", creator="AsapSCIENCE",
        topic="psychology", tags=["dunning-kruger","cognitive-bias","intermediate","mind"],
        duration=58, views=1_200_000, likes=98_000,
        thumbnail_url="https://picsum.photos/seed/ps3/400/700",
        youtube_id="y50i1bI4uDg"),
    ContentItem(id="ps4", title="Как работает дофаминовая система", creator="Huberman Lab Clips",
        topic="psychology", tags=["dopamine","neuroscience","intermediate","behavior","mind"],
        duration=60, views=1_800_000, likes=152_000,
        thumbnail_url="https://picsum.photos/seed/ps4/400/700",
        youtube_id="3cCCXdJOvEo"),

    # ── PRODUCTIVITY ──────────────────────────────────────────────────────────
    ContentItem(id="pr1", title="Метод Помодоро — как использовать", creator="Thomas Frank",
        topic="productivity", tags=["pomodoro","time-management","beginner","study"],
        duration=58, views=1_100_000, likes=91_000,
        thumbnail_url="https://picsum.photos/seed/pr1/400/700",
        youtube_id="mNBmG24djoY"),
    ContentItem(id="pr2", title="Система GTD за 2 минуты", creator="Mike and Matty",
        topic="productivity", tags=["gtd","organization","intermediate","workflow"],
        duration=60, views=670_000, likes=55_000,
        thumbnail_url="https://picsum.photos/seed/pr2/400/700",
        youtube_id="gCswMsONkwY"),
    ContentItem(id="pr3", title="Second Brain — зачем нужна внешняя память", creator="Ali Abdaal",
        topic="productivity", tags=["note-taking","pkm","intermediate","knowledge"],
        duration=59, views=890_000, likes=74_000,
        thumbnail_url="https://picsum.photos/seed/pr3/400/700",
        youtube_id="K-ssUVyfn5g"),

    # ── SCIENCE ──────────────────────────────────────────────────────────────
    ContentItem(id="sc1", title="Квантовая запутанность за 60 сек", creator="Kurzgesagt",
        topic="science", tags=["quantum","physics","intermediate","mind-blowing"],
        duration=60, views=2_400_000, likes=210_000,
        thumbnail_url="https://picsum.photos/seed/sc1/400/700",
        youtube_id="JFozGfxmi8A"),
    ContentItem(id="sc2", title="Как работает CRISPR", creator="TED-Ed",
        topic="science", tags=["crispr","biology","genetics","intermediate"],
        duration=58, views=1_700_000, likes=141_000,
        thumbnail_url="https://picsum.photos/seed/sc2/400/700",
        youtube_id="MnYppmstxIs"),
    ContentItem(id="sc3", title="Тёмная материя — что мы знаем", creator="Kurzgesagt",
        topic="science", tags=["dark-matter","physics","cosmology","intermediate"],
        duration=59, views=1_900_000, likes=162_000,
        thumbnail_url="https://picsum.photos/seed/sc3/400/700",
        youtube_id="HneiEA1B8ks"),
]

CONTENT_MAP: dict[str, ContentItem] = {c.id: c for c in CONTENT}
TOPICS_MAP: dict[str, Topic] = {t.id: t for t in TOPICS}
